### ISSUE TITLE
Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.

### ISSUE THREAD

**Issue by TaufikRafli138** [jeypc/codeigniter4-mail#1]

**Comment by jeypc** [comment]
Config email nya ada yang salah ini mas, untuk mengirim email dengan smtp google sekarang harus menggunakan App Password.
Youtube: [Codeigniter 4 Kirim Email dengan SMPT Gmail tanpa fitur Less Secure app](https://youtu.be/pIBzpJuF7L4).
